# Generated by Django 5.2.1 on 2025-05-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fvectors%2Fblank-profile-picture-mystery-man-973460%2F&psig=AOvVaw3OqqaJjn5tc-GVwFKsKQoB&ust=1748419688323000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCJjQ34aZw40DFQAAAAAdAAAAABAM', null=True, upload_to='customers/'),
        ),
    ]
