# Generated by Django 5.2.1 on 2025-05-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='customers/blank-profile-picture-973460_1280.webp', null=True, upload_to='customers/'),
        ),
    ]
